#玩家默认可创建的抽奖箱数量
#通过给权限dc.maxcreate.数量
#可以提高玩家创建箱子的数量上限，多个权限取最大值
MaxCreateNumber: 2

#每次创建抽奖箱初始所需游戏币
BaseMoney: 1000

#每个抽奖箱最多有多少种物品
MaxSize: 90

#一次最多抽奖多少次？
MaxDrawNumber: 250
#是否在物品不足时开启超上限抽奖（如只剩一个物品，概率0.01%，不开启的话一次只能抽一发（抽奖箱物品数量上限））
ReturnItem: true

#当抽中概率设置...及以下的物品发出公告
RaryProbability: 0.01%

#选择抽奖后如果在...秒内没有输入，则自动结束
Timeout: 5

#最多一个抽奖箱同时绑定...个方块
MaxBind: 1

#禁止指定世界绑定箱子
BlackBind:
  - 'zc'
  - 'fb'

#禁止指定type的物品加到抽奖箱
BlackType:
  - 'STONE'

#禁止指定lore的物品添加到抽奖箱
BlackLore:
  - '绑定物品'

#指定type的方块才能绑定抽奖箱（不填为不启用）
BindWhiteType: [ ]

#每次抽奖的税
#dc.tax是免税权限
Tax: 0.13

#是否开启日志记录
Log: true