name: DemocracyCrate
main: pers.tany.democracycrate.Main
version: 1.0.3
author: tany
description: 玩家自主创建抽奖箱
depend: [ YukiNoaAPI,HolographicDisplays, ]
api-version: 1.13
commands:
  DemocracyCrate:
    usage: /DemocracyCrate
    aliases: [ dc ]
permissions:
  dc.create:
    default: true